title: Ioannis IGI
description: Systems Architect & Academic Supervisor Portfolio Blog
url: "https://ioannisin.github.io"
baseurl: ""

# Plugins για SEO και Sitemap
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
