title: Ioannis IGI
description: Systems Architect & Academic Supervisor Portfolio Blog
url: "https://ioannisin.github.io"
baseurl: ""

# Tech Optimizations
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Liquid Processor Settings
sass:
  style: compressed
